domain:      javier.io
title:       "javier.io"
url:         "javier.io"
author:      "Javier López"
description: "Javier López personal blog"

twitter:
  username: javier_flpz

source:      .
destination: ./_site
plugins:     ./_plugins

gems:
  - jekyll-seo-tag

safe:        false
auto:        false
future:      true
lsi:         true
pygments:    false
markdown:    kramdown
