domain:      javier.io
title:       "javier.io"

source:      .
destination: ./_site
plugins:     ./_plugins

safe:        false
auto:        false
future:      true
lsi:         true
pygments:    false
markdown:    kramdown
